# Generated by Django 6.0.6 on 2026-06-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=70, unique=True, verbose_name='Category Title')),
                ('cat_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=70, verbose_name='Product Title')),
                ('prod_desc', models.CharField(blank=True, max_length=400, null=True, verbose_name='Product Description')),
                ('date_of_add', models.DateField(auto_now=True, verbose_name='Product Date of Add')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('product_image', models.URLField(max_length=400, verbose_name='Product Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shop_app', to='shop_app.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'Products',
            },
        ),
    ]
