# Generated by Django 6.0.6 on 2026-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remain',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Product Remain'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_add',
            field=models.DateField(auto_now_add=True, verbose_name='Product Date of Add'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Price'),
        ),
    ]
