# Generated by Django 6.0.6 on 2026-07-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_product_remain_alter_product_date_of_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shop_app', to='shop_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Детальное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_title',
            field=models.CharField(max_length=70, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=400, verbose_name='Картинка товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remain',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='кол-во на складе'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, verbose_name='Количество товара в корзине')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shop_app.product', verbose_name='Корзина')),
            ],
        ),
    ]
