# Generated by Django 6.0.6 on 2026-07-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='value',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
